### ISSUE TITLE
Time axis differences

### ISSUE THREAD

**Issue by matear** [AusClimateService/bias-correction-data-release#4]
For the bias-adjusted-input data the time coordinate of hursmin/hursmax and the other variables differ.  This causes problems and requires putting the hursmin on the same time axis as pr, tasmax, sfcWindmax before doing calculations with all the variables

I used 
hursmin=hursmin.assign_coords(time= pr.time)

**Comment by DamienIrving** [comment]
Thanks for spotting this, @matear. Next week I'll be processing the ssp126 data so I can reprocess the hursmin/max ssp370 and historical data so the time units are `days since 1950-01-01` like everything else (the time aggregation function to create daily hursmin/max from the hourly hurs data changes the time units, so I need to make it change it back).
