### ISSUE TITLE
Double precision

### ISSUE THREAD

**Issue by matear** [AusClimateService/bias-correction-data-release#5]
All the BoM bias-corrected-input data is in double precision data. Is this necessary because it doubles the storage requirement?

**Comment by DamienIrving** [comment]
Not sure if it's necessary. All the CORDEX data is double precision, so all the pre-processed CORDEX data in `bias-adjustment-input` is also double precision.

**Comment by matear** [comment]
CCAM is not double precision.


Dr.  Richard J. Matear
CSIRO Environment
GPO Box 1538
Hobart, TAS, Australia
7001

(Int+ 61) (3) 62 325 243 (phone)
(Int+ 61) (3) 62 325 000 (fax)
0428 111 314 (mobil)
***@***.******@***.***>
http://people.csiro.au/M/R/Richard-Matear

From: Damien Irving ***@***.***>
Date: Friday, 14 June 2024 at 4:08 pm
To: AusClimateService/bias-correction-data-release ***@***.***>
Cc: Matear, Richard (Environment, Hobart) ***@***.***>, Author ***@***.***>
Subject: Re: [AusClimateService/bias-correction-data-release] Double precision (Issue #5)

Not sure if it's necessary. All the CORDEX data is double precision, so all the pre-processed CORDEX data in bias-adjustment-input is also double precision.

**Comment by DamienIrving** [comment]
Turns out the original BARPA data is stored as `int` with a scale factor and offset provided in the file metadata. When xarray reads the dataset and applies the scale factor and adds the offset it produces a double precision array, hence my pre-processed data files were double precision. The original CCAM data was all stored in single precision (i.e. no scale factor or offset) so it remained single precision throughout the pre-processing.

I've updated the dataset so everything is `float32`.
